apiVersion: apps/v1
kind: Deployment
metadata:
  name: govee-app
  labels: 
    app: govee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: govee
  template:
    metadata:
      labels:
        app: govee
    spec:
      containers:
      - name: govee-app
        image: adnan10101/govee-control-system:test0.0.1
        ports:
        - containerPort: 5000

