apiVersion: v1
kind: Service
metadata:
  name: govee-svc
  labels:
    app: govee-svc
spec:
  type: NodePort
  selector:
    app: govee
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32212